# Lab01: Làm quen với Pytorch

#### Bài 1 

In [1]:
import torch

a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [3]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
tensor_10 = torch.full((5, 5), 10.0)
print("\nTensor 5x5 chứa toàn giá trị 10:\n", tensor_10)

tensor([[0.0434, 0.6974, 0.8790, 0.9906],
        [0.9337, 0.1724, 0.2818, 0.1160],
        [0.3008, 0.8404, 0.3720, 0.5511]])
tensor([[-0.2378, -0.6255, -0.0817,  0.0376],
        [ 0.3720, -0.6045, -1.0140, -0.2014],
        [ 1.4663, -0.4176, -0.0228, -0.6061]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5x5 chứa toàn giá trị 10:
 tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


In [5]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


In [6]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.5596, -0.7897, -1.6574, -0.1559, -0.0654],
         [ 1.5605, -2.7315, -0.7415,  1.5943,  0.0417],
         [ 1.4324, -0.9025, -0.2898,  0.2018, -0.5042],
         [-0.2167,  0.9446,  0.5016, -0.2791, -0.1848]],

        [[-0.2437,  1.3777,  1.5376,  1.6903, -1.6818],
         [ 0.1890, -0.0089, -0.1214,  1.4983,  0.1550],
         [ 0.6666,  0.0446, -0.4382,  1.7063,  1.2715],
         [ 0.3429,  0.9330, -0.2758, -1.3615, -0.7736]],

        [[ 0.0684, -0.6861, -0.7589, -0.9461, -1.0110],
         [ 1.1123,  0.9064, -0.3436, -0.2817, -0.1318],
         [-0.3998, -0.9128,  0.6163,  0.0840, -0.7107],
         [-1.2712,  0.6508, -1.7777,  1.1693, -0.1306]]])

Tensor a[1]:
tensor([[-0.2437,  1.3777,  1.5376,  1.6903, -1.6818],
        [ 0.1890, -0.0089, -0.1214,  1.4983,  0.1550],
        [ 0.6666,  0.0446, -0.4382,  1.7063,  1.2715],
        [ 0.3429,  0.9330, -0.2758, -1.3615, -0.7736]])

Tensor a[1:, 2:4]:
tensor([[[ 0.6666,  0.0446, -0.4382,  1.7063,  1.2

In [8]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
reshaped_2x6 = a.reshape(2, 6)
print("Reshape (2, 6) shape:", reshaped_2x6.shape, "-> Số phần tử:", reshaped_2x6.numel())

Original:
tensor([[ 1.6318,  1.4014,  2.3608, -1.0059],
        [ 0.7572, -0.7691,  1.0783,  1.6641],
        [ 1.1877, -1.2966,  0.2171, -1.2146]])

Flatten:
tensor([ 1.6318,  1.4014,  2.3608, -1.0059,  0.7572, -0.7691,  1.0783,  1.6641,
         1.1877, -1.2966,  0.2171, -1.2146])

Reshape to 3 x 2 x 2:
tensor([[[ 1.6318,  1.4014],
         [ 2.3608, -1.0059]],

        [[ 0.7572, -0.7691],
         [ 1.0783,  1.6641]],

        [[ 1.1877, -1.2966],
         [ 0.2171, -1.2146]]])
Reshape (2, 6) shape: torch.Size([2, 6]) -> Số phần tử: 12
