# Lab01: Làm quen với Pytorch

#### Bài 1 

In [10]:
import torch

a = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    dtype=torch.int32
)

print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### Bài 2

In [11]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)
tensor_10 = torch.full((5, 5), 10.0)
print("\nTensor 5x5 chứa toàn giá trị 10:\n", tensor_10)

tensor([[0.1556, 0.5577, 0.1926, 0.7066],
        [0.7251, 0.3873, 0.9846, 0.6516],
        [0.7101, 0.9165, 0.0704, 0.2429]])
tensor([[ 0.3686,  0.0168, -0.9963,  0.4883],
        [ 0.1288, -0.8648, -1.1867, -0.1352],
        [ 1.0718,  0.1783, -2.6517, -1.3999]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Tensor 5x5 chứa toàn giá trị 10:
 tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]])


### Bài 3

In [12]:
import torch
a = torch.zeros(2, 3, 4)
print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


### Bài 4

In [13]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[-0.6976, -1.2441, -0.9716, -2.0352,  0.8576],
         [ 1.1200, -0.3371, -1.1211,  0.6738, -1.5588],
         [-1.4091, -1.1070, -1.3740,  1.6282, -0.2538],
         [-0.8374,  0.3335,  2.6314, -1.0444,  0.3171]],

        [[ 0.6725,  0.3214,  0.0941,  0.0117,  0.3783],
         [ 0.4054, -1.7745,  0.2988, -0.7402,  1.2081],
         [ 0.8245,  1.8554, -0.8295, -0.6967, -0.8664],
         [-0.6085, -1.8185,  0.9497, -1.0609,  0.9295]],

        [[-1.1073, -0.1695, -0.8265,  0.5200,  2.0638],
         [ 1.2970, -1.5245,  0.0345,  1.3099,  0.5545],
         [ 0.9602,  0.4842,  0.4094,  0.3230,  2.3624],
         [-0.4551, -1.8789,  0.2116, -0.8980, -1.4510]]])

Tensor a[1]:
tensor([[ 0.6725,  0.3214,  0.0941,  0.0117,  0.3783],
        [ 0.4054, -1.7745,  0.2988, -0.7402,  1.2081],
        [ 0.8245,  1.8554, -0.8295, -0.6967, -0.8664],
        [-0.6085, -1.8185,  0.9497, -1.0609,  0.9295]])

Tensor a[1:, 2:4]:
tensor([[[ 0.8245,  1.8554, -0.8295, -0.6967, -0.8

### Bài 5

In [14]:
import torch
a = torch.randn(3, 4)
print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))
reshaped_2x6 = a.reshape(2, 6)
print("Reshape (2, 6) shape:", reshaped_2x6.shape, "-> Số phần tử:", reshaped_2x6.numel())

Original:
tensor([[ 0.7036, -2.1740, -1.4169, -0.0913],
        [-0.1252,  0.4223,  0.0691, -1.3761],
        [-1.8680,  1.1180, -0.6317, -1.5257]])

Flatten:
tensor([ 0.7036, -2.1740, -1.4169, -0.0913, -0.1252,  0.4223,  0.0691, -1.3761,
        -1.8680,  1.1180, -0.6317, -1.5257])

Reshape to 3 x 2 x 2:
tensor([[[ 0.7036, -2.1740],
         [-1.4169, -0.0913]],

        [[-0.1252,  0.4223],
         [ 0.0691, -1.3761]],

        [[-1.8680,  1.1180],
         [-0.6317, -1.5257]]])
Reshape (2, 6) shape: torch.Size([2, 6]) -> Số phần tử: 12


### Bài 6

In [15]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)
print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)
print("Shape của a @ b.T:", (a @ b.T).shape)


a:
tensor([[-1.1418,  0.5104, -0.1389],
        [-0.1331,  0.1530,  0.4774]])
b:
tensor([[ 0.2256, -1.8190,  2.0374],
        [-0.0294,  0.4824, -2.0632]])

a + b:
tensor([[-0.9162, -1.3086,  1.8985],
        [-0.1625,  0.6354, -1.5858]])

a / b:
tensor([[-5.0616, -0.2806, -0.0682],
        [ 4.5286,  0.3172, -0.2314]])

a^2:
tensor([[1.3036, 0.2605, 0.0193],
        [0.0177, 0.0234, 0.2279]])

Matrix multiplication:
tensor([[-1.4690,  0.5664],
        [ 0.6643, -0.9072]])
Shape của a @ b.T: torch.Size([2, 2])


### Bài 7

In [16]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=1))
print("\nStandard deviation:")
print(torch.std(a, dim=1))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=1))

tensor([[-0.2790,  0.9972,  0.3059, -0.3272],
        [-0.8691,  0.0857,  0.0590,  0.6997],
        [ 1.8600,  1.0145,  0.2316,  1.2725]])

Mean:
tensor([ 0.1742, -0.0062,  1.0947])

Standard deviation:
tensor([0.6196, 0.6469, 0.6754])

Cumulative sum:
tensor([[-0.2790,  0.7182,  1.0242,  0.6969],
        [-0.8691, -0.7834, -0.7244, -0.0247],
        [ 1.8600,  2.8745,  3.1061,  4.3786]])


###  Bài 8

In [17]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


### Bài 9 

In [ ]:
import numpy as np
import torch

polynomial = np.poly1d([1, 2, 3])
N = 20
np.random.seed(42)
X = np.random.rand(N, 1) * 5
Y = polynomial(X)

XX = np.hstack([X * X, X, np.ones_like(X)])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(2000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Learned coefficients w:\n", w.detach().numpy().flatten())

IndentationError: expected an indented block after 'for' statement on line 18 (528036015.py, line 19)